package model;
// Generated May 19, 2015 10:36:16 PM by Hibernate Tools 4.3.1

/**
 * Job generated by hbm2java
 */
public class Job implements java.io.Serializable {

    private String id;
    private String title;
    private String description;
    private String requirement;
    private String cname;
    private String ctype;
    private String cindustry;
    private String website;
    private String location;
    private String cdescription;

    public Job() {
    }

    public Job(String id) {
        this.id = id;
    }

    public Job(String id, String title, String description, String requirement, String cname, String ctype, String cindustry, String website, String location, String cdescription) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.requirement = requirement;
        this.cname = cname;
        this.ctype = ctype;
        this.cindustry = cindustry;
        this.website = website;
        this.location = location;
        this.cdescription = cdescription;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getRequirement() {
        return this.requirement;
    }

    public void setRequirement(String requirement) {
        this.requirement = requirement;
    }

    public String getCname() {
        return this.cname;
    }

    public void setCname(String cname) {
        this.cname = cname;
    }

    public String getCtype() {
        return this.ctype;
    }

    public void setCtype(String ctype) {
        this.ctype = ctype;
    }

    public String getCindustry() {
        return this.cindustry;
    }

    public void setCindustry(String cindustry) {
        this.cindustry = cindustry;
    }

    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getCdescription() {
        return this.cdescription;
    }

    public void setCdescription(String cdescription) {
        this.cdescription = cdescription;
    }

    @Override
    public String toString() {
        return this.id+this.cname+this.cindustry+this.cdescription; //To change body of generated methods, choose Tools | Templates.
    }

    
}
