package model;
// Generated May 19, 2015 10:36:16 PM by Hibernate Tools 4.3.1

/**
 * UserJob generated by hbm2java
 */
public class UserJob implements java.io.Serializable {

    private String id;
    private String name;
    private String jid;

    public UserJob() {
    }

    public UserJob(String id) {
        this.id = id;
    }

    public UserJob(String id, String name, String jid) {
        this.id = id;
        this.name = name;
        this.jid = jid;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getJid() {
        return this.jid;
    }

    public void setJid(String jid) {
        this.jid = jid;
    }

}
