package model;
// Generated May 19, 2015 10:36:16 PM by Hibernate Tools 4.3.1

/**
 * Users generated by hbm2java
 */
public class User implements java.io.Serializable {

    private String id;
    private String name;
    private String password;
    private String email;
    private String role;

    public User() {
    }

    public User(String id) {
        this.id = id;
    }

    public User(String id, String name, String password, String email, String role) {
        this.id = id;
        this.name = name;
        this.password = password;
        this.email = email;
        this.role = role;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

}
